# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build, start BE, start FE, test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.1]
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build project
      run: npm install 
  startBE:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Start BE
      run: npm run server &
  startFE:
    needs: startBE
    runs-on: ubuntu-latest
    steps:
    - name: Start FE
      run: npm run start &
  startTests:
    needs: startFE
    runs-on: ubuntu-latest
    steps:
    - name: Start tests
      run: npm test
    
