# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build, start BE, start FE, test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.1]
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build project
      run: npm install 
    - name: Start BE
      run: npm run start-be &
    - name: Start FE
      run: npm run start-fe &
    - name: Download new browsers
      run: npx playwright install
    - name: Start Tests
      run: npm run test
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service-id: ${{ secrets.LIBRARY_ID }}
          api-key: ${{ secrets.LIBRARY_API_KEY }}
          wait_deploy: true 
    
